---
- name: Updates Tunnel 901 on 1b routers to remove old cr319-4z tunnel
  gather_facts: false                                                        # Will skip collecting facts and directly execute tasks listed.
  hosts: router_1b:!cr401-1b:!cr406-1b:!cr832-1b:!cr883-1b                                                # Hosts to be included in this change
  connection: local                                                          # Runs ansible locally
  serial: 10                                                                 # How many hosts Ansible should manage at a single time
  strategy: free                                                             # Allows each host to run until the end of the play as fast as it can

  vars_prompt:
    - name: username
      prompt: "Enter Username"
      private: no

    - name: password
      private: yes
      prompt: "Enter Password"
      confirm: yes

  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"


  tasks:
    - name: Gather ios facts and verify model
      ios_facts:
        gather_subset: all
        provider: "{{ cli }}"

    - name: Update Tunnel 901                                                # Name of task to be executed
      ios_config:                                                            # Cisco module
        provider: "{{ cli }}"                                                # A dict object containing connection details.
        lines:                                                               # The ordered set of commands that should be configured in the section
           -  no ip nhrp map 10.31.212.1 161.181.48.20                       # Old cr319-4z mapping
           -  no ip nhrp map multicast 161.181.48.20                         # Old cr319-4z mapping
           -  no ip nhrp nhs 10.31.212.1                                     # Old cr319-4z mapping
        parents: interface Tunnel 901                                        # The ordered set of parents that uniquely identify the section or hierarchy the commands should be checked against
      when: '"ip nhrp map 10.31.212.1 161.181.48.20" in ansible_net_config'  # When condition is met
      notify: "save ios"                                                     # Calls in the "save ios" handler and executes it.

  handlers:                                                                  # Are triggered at the end of each block of tasks in a play, and will only be triggered once even if notified by multiple different tasks.
    - name: save ios                                                         # Name of the handler
      ios_command:                                                           # Cisco module
        provider: "{{ cli }}"                                                # A dict object containing connection details.
        commands: "write mem"                                                # Command to be executed when this handler is called
      register: saved                                                        # Captures the output of this task as a variable.
      when: not ansible_check_mode                                           # Boolean for skipping an error check during --check
    - debug:                                                                 # This module prints statements during execution and can be useful for debugging variables or expressions without necessarily halting the playbook
        msg: "{{ saved.stdout_lines }}"                                      # The customized message that is printed. If omitted, prints a generic message. This case, it prints out the variable, named "saved" from the output from the handler execution.
